/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programa;

import Modelo.Calcular;

/**
 *
 * @author Dell-9BQM7S1
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxfPrimeiroNumero = new javax.swing.JTextField();
        TxfSegundoNumero = new javax.swing.JTextField();
        BtnSomar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        LblResultado = new javax.swing.JLabel();
        BtnMultiplicacao = new javax.swing.JButton();
        BtnDivisao = new javax.swing.JButton();
        BtnSubtracao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite o primeiro numero:");

        jLabel2.setText("Digite o segundo numero:");

        TxfPrimeiroNumero.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TxfPrimeiroNumeroActionPerformed(evt);
            }
        });

        BtnSomar.setText("+");
        BtnSomar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnSomarActionPerformed(evt);
            }
        });

        BtnMultiplicacao.setText("*");
        BtnMultiplicacao.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnMultiplicacaoActionPerformed(evt);
            }
        });

        BtnDivisao.setText("/");
        BtnDivisao.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnDivisaoActionPerformed(evt);
            }
        });

        BtnSubtracao.setText("-");
        BtnSubtracao.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnSubtracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TxfPrimeiroNumero, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(TxfSegundoNumero)
                    .addComponent(jLabel3)
                    .addComponent(LblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BtnMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BtnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BtnSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TxfPrimeiroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxfSegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSomar)
                    .addComponent(BtnSubtracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDivisao)
                    .addComponent(BtnMultiplicacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblResultado)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxfPrimeiroNumeroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TxfPrimeiroNumeroActionPerformed
    {//GEN-HEADEREND:event_TxfPrimeiroNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfPrimeiroNumeroActionPerformed

    private void BtnSomarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnSomarActionPerformed
    {//GEN-HEADEREND:event_BtnSomarActionPerformed
      Calcular adicao= new Calcular();
      
      String resul = adicao.Calcular(TxfPrimeiroNumero.getText(),TxfSegundoNumero.getText(),"+");
      LblResultado.setText(resul);
    
        
    }//GEN-LAST:event_BtnSomarActionPerformed

    private void BtnMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnMultiplicacaoActionPerformed
    {//GEN-HEADEREND:event_BtnMultiplicacaoActionPerformed
        Calcular multiplicacao=new Calcular();
        String resul= multiplicacao.Calcular(TxfPrimeiroNumero.getText(),TxfSegundoNumero.getText(),"*");
        LblResultado.setText(resul);
    }//GEN-LAST:event_BtnMultiplicacaoActionPerformed

    private void BtnDivisaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnDivisaoActionPerformed
    {//GEN-HEADEREND:event_BtnDivisaoActionPerformed
        Calcular divisao=new Calcular();
        String resul=divisao.Calcular(TxfPrimeiroNumero.getText(),TxfSegundoNumero.getText(),"/");
        LblResultado.setText(resul);
    }//GEN-LAST:event_BtnDivisaoActionPerformed

    private void BtnSubtracaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnSubtracaoActionPerformed
    {//GEN-HEADEREND:event_BtnSubtracaoActionPerformed
      Calcular subtracao=new Calcular();
      String resul= subtracao.Calcular(TxfPrimeiroNumero.getText(),TxfSegundoNumero.getText(),"-");
      LblResultado.setText(resul);
    }//GEN-LAST:event_BtnSubtracaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDivisao;
    private javax.swing.JButton BtnMultiplicacao;
    private javax.swing.JButton BtnSomar;
    private javax.swing.JButton BtnSubtracao;
    private javax.swing.JLabel LblResultado;
    private javax.swing.JTextField TxfPrimeiroNumero;
    private javax.swing.JTextField TxfSegundoNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
